api integration with axios
milan0827/API-Integration pull request #1
Opened 2024-01-29 14:51 UTC by milan0827

A simple UI and performing CRUD operation using axios.
json-server is a package manager for creating simple REST API which was used for this project to perofrom CRUD operation and testing purpose.

This is a simple user form 👇
![Screenshot 2024-01-29 203154](https://github.com/milan0827/API-Integration/assets/76481771/9e071317-852f-43f7-abc9-8f598788aa07)

2024-01-29 15:13 UTC, sarojghalan requested changes
nice your logic are really increasing, 
but still minor changes are need to me fix

2024-01-29 15:13 UTC, sarojghalan commented on src/services/apiServices.ts
its a nice process, but how would you handle `error` and `success` message. 

creating an instance of `axios` would be nice, https://axios-http.com/docs/instance. 

and whenever you want which request can be handled easily with,

2024-01-29 15:13 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +    };
```suggestion
 createUser(...data)
```

2024-01-29 15:13 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +  const [userData, setUserData] = useState<UserDataType[]>([]);
is this is used or ?

2024-01-29 16:07 UTC, milan0827 commented on src/services/apiServices.ts
I will researching more on axios instance,

2024-01-29 16:08 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
> +    };
const newData = {
      firstName: data.firstName,
      lastName: data.lastName,
      email: data.email,
      age: data.age,
      address: data.address,
      country: data.country,
      city: data.city,
      gender: data.gender,
      martialStatus: data.martialStatus,
    };
As these were unnecessary, so these lines of codes were removed

2024-01-29 16:08 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
> +  const [userData, setUserData] = useState<UserDataType[]>([]);
No it was not used and removed in the updated code

2024-01-30 03:43 UTC, sarojghalan requested changes
nice, a lot of new features has been implemented ,

still minor changes are required in new features :rose:

2024-01-30 03:43 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +    createUser(data);
handle success and error message

2024-01-30 03:43 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
i think validation is missing, handle validation precisely

2024-01-30 03:43 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +import { UserDataType } from "../../shared/type";
handle import with absolute import.

2024-01-30 03:43 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +      <button className="bg-blue-400 p-4 text-gray-200">Submit</button>
```suggestion
      <button type="submit" className="bg-blue-400 p-4 text-gray-200">Submit</button>
```

2024-01-30 03:43 UTC, sarojghalan commented on src/services/apiServices.ts
implement , `interceptor` to handle our request before `request` and `response` .

2024-01-30 07:24 UTC, sarojghalan requested changes
nice bhai, Surra :smile: 
but it got comments :smiley:

2024-01-30 07:24 UTC, sarojghalan commented on src/services/apiServices.ts
> +}
i think these are now hooks now you can separate it. 

as our `apiServices` will only have context about network .

2024-01-30 07:24 UTC, sarojghalan commented on src/services/apiServices.ts
> +}
research on where you should place hooks

2024-01-30 16:02 UTC, sarojghalan requested changes
nice bhai, 

still minor changes are need to be done.

2024-01-30 16:02 UTC, sarojghalan commented on src/index.css
>    .input {
what if we have another input but with different ui structure.

2024-01-30 16:02 UTC, sarojghalan commented on src/pages/TableView/index.tsx
> +    <>
wrapping it with section main tag would be nice.

2024-01-30 16:02 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
validation missing

2024-01-30 16:02 UTC, sarojghalan commented on src/services/apiServices.ts
we will talk about this tomorrow.

2024-01-30 16:02 UTC, sarojghalan commented on src/utils/helpers.ts
we will talk about this file, tomorrow

2024-02-01 16:28 UTC, sarojghalan requested changes
Nice  now, Research on `zod` ,
its a validation helper
Still minor changes are need to fix

2024-02-01 16:28 UTC, sarojghalan commented on src/hooks/useDelete.tsx
> +      return data;
is returning data necessary?

2024-02-01 16:28 UTC, sarojghalan commented on src/pages/TableView/index.tsx
> +const BASE_URL = "http://localhost:3000/user";
we have, base url on service so why this is here

2024-02-01 16:28 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
> +    for (let i = 0; i < userDataValues.length; i++) {
we will talk on this tomorrow

2024-02-01 17:16 UTC, milan0827 commented on src/pages/TableView/index.tsx
> +    <>
yes, you are correct

2024-02-02 09:27 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
> +    createUser(data);
All success and error are set dai

2024-02-02 09:28 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
I have done all the validation, you can review it.

2024-02-02 09:29 UTC, milan0827 commented on src/services/apiServices.ts
> +}
I have created the custom hooks and placed it separate files.

2024-02-02 09:30 UTC, milan0827 commented on src/index.css
>    .input {
I hvae to research on this one.

2024-02-02 09:32 UTC, milan0827 commented on src/hooks/useDelete.tsx
> +      return data;
Actually it's not and I hvae removed.

2024-02-02 09:35 UTC, milan0827 commented on src/pages/TableView/index.tsx
> +const BASE_URL = "http://localhost:3000/user";
you are right daii and I have removed.

2024-02-02 09:36 UTC, milan0827 commented
Thanks @sarojghalan  daiii for your amazing guidance

2024-02-02 09:37 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
> +import { UserDataType } from "../../shared/type";
Yes, I have done it, you can review my code.

2024-02-06 00:58 UTC, sarojghalan requested changes
nice bhai, you are rocking 

keep up the pace :rose:

2024-02-06 00:58 UTC, sarojghalan commented on src/hooks/useFetch.tsx
nice, bhai

2024-02-06 00:58 UTC, sarojghalan commented on src/pages/UserForm.tsx/index.tsx
is validation still missing or what ?

2024-02-06 00:58 UTC, sarojghalan commented on src/routes/routes.tsx
you have define routes, as of now we do not need loader, try to implement loader too for future easiness, 

lazy, loading - follow official react router docs

2024-02-06 04:36 UTC, milan0827 commented on src/hooks/useFetch.tsx
Dhanyabaad daii

2024-02-06 04:37 UTC, milan0827 commented on src/routes/routes.tsx
okay, I will research on that.

2024-02-06 04:37 UTC, milan0827 commented on src/pages/UserForm.tsx/index.tsx
No, It's not missing, All the validation are working fine.

2024-02-06 11:56 UTC, merged